### ISSUE TITLE
FTP error "remote file not found"

### ISSUE THREAD

**Issue by JSP6668** [ctlcltd/e2-sat-editor#12] opened 2024-01-18 11:09 UTC
### Describe the bug

Hi, 

thank you for developing this, it looks ver nice, however I cannot download any data:

I think configured the connection properbly, it say "FTP connection establised sucessfully" but when I want to download
config and buquets it claims FTP error "remote file not found". I did used the correct path in the settings for the sattellities .xml etc.

I treid with the AppImage and the Flatpak Version, same problem. I use debian bookworm (gnome).

Thank You for your Help

### Steps to reproduce

1. enter credentials, IP and path(s) in settings
2. try to connect (connect button)
3. Download receiver data
4. error

### Expected behavior

sucessful Download of receiver Data

### Software version

1.1

### Download medium

GitHub Releases page

### Platform running

I don't know

### Architecture running

I don't know

**Comment by ctlcltd** [comment] 2024-01-19 20:09
On versions prior to 1.0 there may be problems with FTP. You said version 1.1.

Can you provide me more information? In the **Configuration** group of the connection profile: Transponders path, Services path, Bouquets path.
> For help with Settings (Connection settings) the Online Help [https://e2sateditor.com/help/settings.html#connection](https://e2sateditor.com/help/settings.html#connection)
For help Troubleshooting (FTP) the Online Help [https://e2sateditor.com/help/troubleshooting.html#ftp](https://e2sateditor.com/help/troubleshooting.html#ftp)

Thank you

**Comment by ctlcltd** [comment] 2024-01-19 20:15
If you can attach me an FTP log of the software in this issue. Otherwise it's the same.

### Enable FTP debug
FTP debugging is disabled by default to avoid slowing down execution.

It can be useful to solve problems and report issues on the GitHub repository.

Note: *FTP debugging may not be available on Windows PowerShell.*

*Recommendation: Do not do this if you do not understand what you are doing.*

To enable FTP debugging, go to **"Settings"** > **Advanced** > [confirm].

Change the `ftpcom.debug` line from FALSE to TRUE, typing `true`.

Save your settings by pressing **"Save"** and close the software.

Open a terminal window and launch the software from its current location.

Press **"Connect"** and **"Disconnect"** from quick menu to attempt an FTP connection.

All FTP messages will be shown in the terminal.

To attach the log to the issue, select all the output and **Copy**, **Paste** to a plain text file.

Next, disable FTP debugging, change the `ftpcom.debug` line from TRUE to FALSE again, typing `false`.

**Comment by JSP6668** [comment] 2024-01-19 22:24
Hi, I enabled the FTP debugging, find the output attached.

Here are the path that i used (I checked via ssh, system is openatv):

Transponders: /etc/
Services: /etc/enigma2/
Bouquets: /etc/enigma2/
Picos: /media/hdd/picon

[connect-download.txt](https://github.com/ctlcltd/e2-sat-editor/files/13995105/connect-download.txt)
[connect-disconnect.txt](https://github.com/ctlcltd/e2-sat-editor/files/13995106/connect-disconnect.txt)

**Comment by JSP6668** [comment] 2024-01-19 22:32
Regarding your connection help site, Itried other path as well, but no success.

Transponders: /etc/enigma2/
Services: /etc/tuxbox/
Bouquets: /etc/enigma2/
Picos: /media/hdd/picon

**Comment by ctlcltd** [comment] 2024-01-19 22:44
Thank you, this is very helpful. I need to investigate further. It seems
there are no files listed.

**Comment by ctlcltd** [comment] 2024-01-20 10:12
### Most common connection settings

Parameters, Username, Password, vary by STB, rely on specialistic forum on the internet.

#### Enigma 2.4 and 2.3
Transponders: /etc/tuxbox
Services: /etc/enigma2
Bouquets: /etc/enigma2

#### Enigma 2.4
Transponders: /var/usr/local/share/enigma2/defaults
Services: /var/usr/local/share/enigma2/defaults
Bouquets: /var/usr/local/share/enigma2/defaults

#### Octagon Gx-NationalChip Enigma 2.4
Transponders: /home/gx/local/enigma_db
Services: /home/gx/local/enigma_db
Bouquets: /home/gx/local/enigma_db

#### Enigma 1
Transponders: /var/etc
Services: /var/tuxbox/config/enigma
Bouquets: /var/tuxbox/config/enigma

#### Neutrino
Transponders: /var/tuxbox/config
Services: /var/tuxbox/config/zapit
Bouquets: /var/tuxbox/config/zapit

#### Triple Dragon
Transponders: /var/share/dvb2001
Services: /var/share/dvb2001
Bouquets: /var/share/dvb2001

#### WeTek Play
Transponders: /data/data/com.amlogic.tvservice/databases
Services: /data/data/com.amlogic.tvservice/databases
Bouquets: /data/data/com.amlogic.tvservice/databases

&nbsp;

Picons: /usr/share/enigma2/picon
Picons: /usr/share/enigma2/picon_oled
Picons: /media/usb/picons
Picons: /media/hdd/picons
Picons: /data/picon

Note: *the software does not currently upload/download picon images, these must be uploaded manually to the STB*
&nbsp;
Telnet command: init 3
Telnet command: systemctl restart enigma2

**Comment by ctlcltd** [comment] 2024-01-20 10:22
The log only shows the file *AutoBouquetsMaker*, it looks like a directory. The connection parameters could be wrong.
Try using **Enigma 2.4 and 2.3** parameters, with Transponders path: `/etc/tuxbox`
I have an Edision Gx-NationalChip STB and I tested with it.
For **OpenATV** the parameters should be **Enigma 2.4 and 2.3** but I can't know it's sure.

**Comment by ctlcltd** [comment] 2024-01-20 10:46
> Transponders: /etc/enigma2/
Services: /etc/tuxbox/
Bouquets: /etc/enigma2/

@JSP6668 thanks, there is an error in the example in Online Help, now corrected

Transponders: /etc/tuxbox
Services: /etc/enigma2
Bouquets: /etc/enigma2

**Comment by ctlcltd** [comment] 2024-01-20 20:02
I reproduced the issue in a test environment.
There's a bug. A directory inside the paths interrupts the download. FTP should be more fault tolerant.
**I'm releasing a minor version 1.1.1, it should be available next 24-48 hours.**

**Comment by ctlcltd** [comment] 2024-02-02 09:16
Fixed on release [v1.1.1](../releases/tag/v1.1.1)

**Closed by ctlcltd** 2024-02-02 09:16 UTC
Labels: bug
