### ISSUE TITLE
segmentation fault on opensuse tumbleweed

### ISSUE THREAD

**Issue by ahmedmoselhi** [ctlcltd/e2-sat-editor#23] opened 2024-07-10 14:30 UTC
### Describe the bug

When I open my channels database in program and try to save I get segmentation fault. I tried to run from terminal and here is the log:

```
$e2-sat-editor 
qt.svg: <input>:237:10: Could not resolve property: #linearGradient8471
qt.svg: <input>:237:10: Could not resolve property: #linearGradient8473
inotify_add_watch(/var/lib/samba/usershares) failed: (Permission denied)
Segmentation fault (core dumped)
```

### Steps to reproduce

1. open the program
2. load channels data
3. try to save changes

### Software version

1.5

### Download medium

other (please specify)

### Platform running

Linux KDE

### Architecture running

x86_64 (64-bit)

### Other (please specify)

custom built rpm from spec file [here](https://build.opensuse.org/package/show/home:ahmedmoselhi2/e2-sat-editor)

### Log

```shell
2024-07-10 17:29:23.214757 <Debug> [e2se.gui] gui::gui
2024-07-10 17:29:23.362995 <Debug> [e2se.gui] gui::updateSettings
2024-07-10 17:29:23.363160 <Debug> [e2se.gui] gui::gui  language preference: system
2024-07-10 17:29:23.363258 <Debug> [e2se.gui] gui::gui  language loaded: en_US
2024-07-10 17:29:23.363429 <Debug> [e2se.gui] gui::layout
2024-07-10 17:29:23.363455 <Debug> [e2se.gui] gui::menuBarLayout
2024-07-10 17:29:23.367192 <Debug> [e2se.gui] gui::statusBarLayout
2024-07-10 17:29:23.459442 <Debug> [e2se.gui] gui::tabStackerLayout
2024-07-10 17:29:23.465837 <Debug> [e2se.gui] gui::launcher
2024-07-10 17:29:23.465855 <Debug> [e2se.gui] gui::updateMenu
2024-07-10 17:29:23.465917 <Debug> [e2se.gui] tab::tab
2024-07-10 17:29:23.465936 <Debug> [e2se.gui] gui::newTab  ttid: 776667744
2024-07-10 17:29:23.465941 <Debug> [e2se.gui] tab::viewMain
2024-07-10 17:29:23.465950 <Debug> [e2se.gui] dataHandler::dataHandler
2024-07-10 17:29:23.465954 <Debug> [e2se.gui] ftpHandler::ftpHandler
2024-07-10 17:29:23.465958 <Debug> [e2se.gui] tools::tools
2024-07-10 17:29:23.465966 <Debug> [e2se.gui] mainView::mainView
2024-07-10 17:29:23.465975 <Debug> [e2se.gui] mainView::layout
2024-07-10 17:29:23.546250 <Debug> [e2se.gui] tab::layout
2024-07-10 17:29:23.546686 <Debug> [e2se.gui] tab::ftpComboItems
2024-07-10 17:29:23.572988 <Debug> [e2se.gui] tab::newFile
2024-07-10 17:29:23.573014 <Debug> [e2se.gui] tab::reset
2024-07-10 17:29:23.573019 <Debug> [e2se.gui] mainView::reset
2024-07-10 17:29:23.573386 <Debug> [e2se.gui] mainView::updateReferenceBox
2024-07-10 17:29:23.573400 <Debug> [e2se.gui] gui::resetStatusBar
2024-07-10 17:29:23.573405 <Debug> [e2se.gui] dataHandler::newFile
2024-07-10 17:29:23.573422 <Debug> [e2se.e2db] e2db_parser::e2db_parser
2024-07-10 17:29:23.573428 <Debug> [e2se.e2db] e2db_maker::e2db_maker
2024-07-10 17:29:23.573432 <Debug> [e2se.e2db] e2db_converter::e2db_converter
2024-07-10 17:29:23.573436 <Debug> [e2se.e2db] e2db::e2db
2024-07-10 17:29:23.573444 <Debug> [e2se.gui] e2db::e2db
2024-07-10 17:29:23.573448 <Debug> [e2se.gui] e2db::setup
2024-07-10 17:29:23.573545 <Debug> [e2se.gui] e2db::primer
2024-07-10 17:29:23.573618 <Debug> [e2se.gui] e2db::add_bouquet  bname: bouquets.tv
2024-07-10 17:29:23.573627 <Debug> [e2se.gui] e2db::add_bouquet  bname: bouquets.radio
2024-07-10 17:29:23.573632 <Debug> [e2se.gui] tab::load
2024-07-10 17:29:23.573636 <Debug> [e2se.gui] mainView::load
2024-07-10 17:29:23.573640 <Debug> [e2se.gui] gui::updateMenu
2024-07-10 17:29:23.573651 <Debug> [e2se.gui] mainView::load  bouquet: bouquets.tv
2024-07-10 17:29:23.573673 <Debug> [e2se.gui] mainView::load  bouquet: bouquets.radio
2024-07-10 17:29:23.573704 <Debug> [e2se.gui] mainView::servicesItemChanged
2024-07-10 17:29:23.573710 <Debug> [e2se.gui] mainView::allowDnd
2024-07-10 17:29:23.573721 <Debug> [e2se.gui] mainView::populate  current: chs
2024-07-10 17:29:23.573817 <Debug> [e2se.gui] mainView::updateFlags
2024-07-10 17:29:23.573842 <Debug> [e2se.gui] mainView::updateStatusBar
2024-07-10 17:29:23.573847 <Debug> [e2se.gui] gui::setStatusBar
2024-07-10 17:29:23.573861 <Debug> [e2se.gui] mainView::populate  current: chs
2024-07-10 17:29:23.573935 <Debug> [e2se.gui] mainView::updateFlags
2024-07-10 17:29:23.573941 <Debug> [e2se.gui] mainView::updateStatusBar
2024-07-10 17:29:23.573945 <Debug> [e2se.gui] e2db::get_lamedb_version  version: 4
2024-07-10 17:29:23.573949 <Debug> [e2se.gui] e2db::get_zapit_version  version: -1
2024-07-10 17:29:23.573954 <Debug> [e2se.gui] gui::setStatusBar
2024-07-10 17:29:23.599113 <Debug> [e2se.gui] gui::tabChanged  current: 776667744
2024-07-10 17:29:23.599140 <Debug> [e2se.gui] tab::tabSwitch
2024-07-10 17:29:23.599146 <Debug> [e2se.gui] gui::updateMenu
2024-07-10 17:29:23.599155 <Debug> [e2se.gui] mainView::updateStatusBar
2024-07-10 17:29:23.599159 <Debug> [e2se.gui] e2db::get_lamedb_version  version: 4
2024-07-10 17:29:23.599168 <Debug> [e2se.gui] e2db::get_zapit_version  version: -1
2024-07-10 17:29:23.599174 <Debug> [e2se.gui] gui::setStatusBar
2024-07-10 17:29:23.599197 <Debug> [e2se.gui] mainView::updateStatusBar
2024-07-10 17:29:23.599202 <Debug> [e2se.gui] gui::setStatusBar
2024-07-10 17:29:23.599212 <Debug> [e2se.gui] mainView::update
2024-07-10 17:29:23.599216 <Debug> [e2se.gui] gui::tabViewChanged  ttv: 0
2024-07-10 17:29:23.708212 <Debug> [e2se.gui] gui::clipboardDataChanged
2024-07-10 17:29:23.708244 <Debug> [e2se.gui] tab::clipboardDataChanged
2024-07-10 17:29:23.708255 <Debug> [e2se.gui] mainView::clipboardDataChanged
2024-07-10 17:29:23.709738 <Debug> [e2se.gui] gui::windowChanged  mwind: busy
2024-07-10 17:29:23.709764 <Debug> [e2se.gui] gui::updateMenu
2024-07-10 17:29:27.812981 <Debug> [e2se.gui] gui::clipboardDataChanged
2024-07-10 17:29:27.813057 <Debug> [e2se.gui] tab::clipboardDataChanged
2024-07-10 17:29:27.813090 <Debug> [e2se.gui] mainView::clipboardDataChanged
2024-07-10 17:29:28.352148 <Debug> [e2se.gui] gui::clipboardDataChanged
2024-07-10 17:29:28.352228 <Debug> [e2se.gui] tab::clipboardDataChanged
2024-07-10 17:29:28.352257 <Debug> [e2se.gui] mainView::clipboardDataChanged
2024-07-10 17:29:28.607497 <Debug> [e2se.gui] gui::tabAction  bit: 254
2024-07-10 17:29:28.607563 <Debug> [e2se.gui] tab::actionCall  bit: 254
2024-07-10 17:29:28.607585 <Debug> [e2se.gui] tab::toolsInspector
2024-07-10 17:29:28.607599 <Debug> [e2se.gui] tools::inspector
2024-07-10 17:29:28.670236 <Debug> [e2se.gui] gui::clipboardDataChanged
2024-07-10 17:29:28.670263 <Debug> [e2se.gui] tab::clipboardDataChanged
2024-07-10 17:29:28.670270 <Debug> [e2se.gui] mainView::clipboardDataChanged
2024-07-10 17:29:28.720345 <Debug> [e2se.gui] gui::clipboardDataChanged
2024-07-10 17:29:28.720375 <Debug> [e2se.gui] tab::clipboardDataChanged
2024-07-10 17:29:28.720383 <Debug> [e2se.gui] mainView::clipboardDataChanged
2024-07-10 17:29:28.721787 <Debug> [e2se.gui] gui::windowChanged  mwind: busy
2024-07-10 17:29:28.721811 <Debug> [e2se.gui] gui::updateMenu
```

**Comment by ctlcltd** [comment] 2024-07-10 22:15
Unfortunately the log does not contain any useful information.
I would need the full log until interruption SEGFAULT.

Can you reproduce the crash with the same actions?
If you can launch the software from terminal, reproduce the same actions and take the log directly from terminal:
`e2-sat-editor --debug`
or
`DEBUG=1 e2-sat-editor`

Crash occurrs after saving? After pressing Save from file dialog?

If there are no write permissions it should show an error, I did a try removing write permissions and it show correctly.
You saved to a network drive? This output: `inotify_add_watch(/var/lib/samba/usersshares) failed: (Permission denied)`, but it could be a line due to file dialog.
qt.svg could be an output from theming, there are no svgs and gradients in the software.

Thank you

**Comment by ctlcltd** [comment] 2024-07-15 12:42
I did a further test on Linux, there was no crash during saving phase.

I do not have enough informations.

You can proceed as follows:
- answer the questions above (steps to reproduce the issue)
- provide the file used (only content compliant with GitHub rules)
- it is a user custom build, try the official release from this repo (AppImage) or official distribution channels (Flathub, Snapcraft)
- try the same actions and saving with "enigma_db" list from repository: https://github.com/ctlcltd/e2se-seeds

Thank you

**Comment by ctlcltd** [comment] 2024-07-18 16:31
There was a bug involving empty service parameters.
Fixed with the commit https://github.com/ctlcltd/e2-sat-editor/commit/c69f8c2239bff47906e9b023fd29e97759095756
@ahmedmoselhi a new version will be released soon, if you encounter this bug again reopen the issue

**Closed by ctlcltd** 2024-07-18 16:31 UTC
Labels: bug
